# Generated by Django 4.2.5 on 2025-04-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrapi", "0007_meeting_participants"),
    ]

    operations = [
        migrations.AddField(
            model_name="project_assign",
            name="status",
            field=models.CharField(
                choices=[("pending", "pending"), ("completed", "completed")],
                default="pending",
                max_length=20,
            ),
        ),
    ]
