# Generated by Django 4.2.5 on 2025-04-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="login_time",
            field=models.TimeField(),
        ),
    ]
